
title: Boulder BugMash
description: Contribute to Open Source Software by getting together in a group and mashing bugs.
upcoming: Our Next BugMash:<br> Saturday, May 4th 11am-5pm @ Gnip's offices.</p> RSVP at <a href="http://gathers.us/events/boulder-rails-bugmash-may-the-4th">gathers.us</a>.
excludes: ["CNAME"]
markdown: maruku
pygments: true
