
title: Boulder BugMash
description: Contribute to Open Source Software by getting together in a group and mashing bugs.
upcoming: Our Next BugMash:<br> Saturday, August 17th 11am-5pm @ Gnip's offices.</p> RSVP at <a href="http://gathers.us/events/boulder-bugmash-august-2013-312ca">gathers.us</a>.
excludes: ["CNAME"]
markdown: maruku
pygments: true
